services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cre8ai_app
    ports:
      - "9090:7860"
    volumes:
      - ./db:/app/db
      - ./data:/app/data
      - hf_cache:/app/cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

volumes:
  hf_cache:
