services:
  app:
    image: shayanshahzad/hassan:v4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cre8ai_app
    ports:
      - "9090:7860"
    volumes:
      - ./db:/app/db
      - ./data:/app/data
      - hf_cache:/app/cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY_1=${GROQ_API_KEY_1}
      - GROQ_API_KEY_2=${GROQ_API_KEY_2}
      - GROQ_API_KEY_3=${GROQ_API_KEY_3}
      - GROQ_API_KEY_4=${GROQ_API_KEY_4}
      - GROQ_API_KEY_5=${GROQ_API_KEY_5}
    env_file:
      - .env
    restart: always

volumes:
  hf_cache:
