services:
  app:
    image: shayanshahzad/hassan:v4
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cre8ai_app
    ports:
      - "9090:7860"
    volumes:
      - ./db:/app/db
      - ./data:/app/data
      - hf_cache:/app/cache/huggingface
    environment:
      - PYTHONUNBUFFERED=1
      - GROQ_API_KEY_1=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
      - GROQ_API_KEY_2=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
      - GROQ_API_KEY_3=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
      - GROQ_API_KEY_4=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
      - GROQ_API_KEY_5=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
    restart: always

volumes:
  hf_cache:
